.\" 
.TH "sdlBrt" "1" "July 2007" "" "User Commands"
.SH "NAME"
sdlBrt \- sdlBasic runtime
.SH "SYNTAX"
sdlBrt [option] foo.sdlbas
.SH "DESCRIPTION"
sdlBrt is the runtime interpreter of sdlBasic, a small, efficient and multiplatform BASIC interpreter aimed to game creation using the power of SDL library. It was inspired by the old and glorious AMOS.
.SH "OPTIONS"
Options:
.TP 
\fB\-\-nosound\fR
disable sound
.TP 
\fB\-\-nosocket\fR
disable socket commands
.TP 
\fB\-\-nodefaults\fR
disable creation of default display
.TP 
\fB\-\-debug\fR
start the program step by step
.TP 
\fB\-\-version\fR
software version
.TP 
\fB\-\-license\fR
license of software
.TP 
\fB\-\-copyright\fR
credits of software
.TP 
\fB\-\-help\fR
this help
.SH "SEE ALSO"
The homepage of sdlBasic can be found at
.B http://www.sdlbasic.altervista.org/
