.\" 
.TH "sdlBasic" "1" "July 2007" "" "User Commands"
.SH "NAME"
sdlBasic \- sdlBasic program editor
.SH "SYNTAX"
sdlBrt [file ..]
.SH "DESCRIPTION"
sdlBrt is a graphical GTK+ based editor based on SciTE for programming games in sdlBasic, a small, efficient and multiplatform BASIC interpreter aimed to game creation using the power of SDL library. It was inspired by the old and glorious AMOS.
.SH "SEE ALSO"
The homepage of sdlBasic can be found at
.B http://www.sdlbasic.altervista.org/
