.TH OLEO 1
.SH NAME
oleo \- the GNU spreadsheet program
.SH SYNOPSIS
.B oleo
[options] [file]
.SH DESCRIPTION
Full documentation for 
.B oleo
is available in GNU
.B info
format.  View it with one of the stand-alone info viewers
.IP
.B "info oleo"
.IP
.B "pinfo oleo"
.IP
.B "tkinfo oleo"
.P
Or view it inside
.B emacs
or
.B xemacs
in the usual way
.IP
.B "C-h i g (oleo) RET"
.SH EXAMPLES
.I /usr/share/doc/oleo/examples/irs-1992.oleo.gz
is a 1992 United States tax return.  It can be viewed in
.B oleo
by first copying and decompressing it.
.IP
.B cp\ /usr/share/doc/oleo/examples/irs-1992.oleo.gz\ .
.br
.B gunzip irs-1992.oleo.gz
.br
.B oleo irs-1992.oleo
