.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENROCKET 1 "March 13, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
openrocket \- model rocket design and simulation
.SH SYNOPSIS
.B openrocket
.SH DESCRIPTION
\fBopenrocket\fP is a free, fully featured model rocket simulator that allows 
you to design and simulate your rockets before actually building and 
flying them.

\fBopenrocket\fP features a full six-degree-of-freedom simulation, realistic 
wind modeling, a multitude of different components including free-form 
and canted fins, clustering and staging. 

.SH SEE ALSO
This program is documented fully at 
http://openrocket.sourceforge.net/documentation.html
.SH AUTHOR
openrocket was written by Sampo Niskanen.
.PP
This manual page was written by Bdale Garbee <bdale@gag.com>
for the Debian project (and may be used by others).
