--- Makefile.old	2011-03-20 14:31:40.000000000 -0400
+++ Makefile	2011-03-20 14:31:55.000000000 -0400
@@ -1,22 +1,22 @@
 # Change these to customize for your setup
-CC=gcc
-CFLAGS=-g -Wall
+#CC=gcc
+#CFLAGS=-g -Wall
 
 # Install paths and command on recommendation from Peter Pentchev
 INSTALL=/usr/bin/install -c
 
 # Some prefer /usr/local over /usr as installation root
 #INSTALL_PATH=/usr/local
-INSTALL_PATH=/usr
+INSTALL_PATH=$(DESTDIR)/usr
 
 BINDIR=$(INSTALL_PATH)/bin
-MAN1DIR=$(INSTALL_PATH)/man/man1
+MAN1DIR=$(INSTALL_PATH)/share/man/man1
 
 # BSD might prefer this
-# DOCPATH=$(INSTALL_PATH)/share/doc/hodie
+DOCDIR=$(INSTALL_PATH)/share/doc/hodie-1.4
 
 # Linux might prefer this:
-DOCDIR=$(INSTALL_PATH)/doc/packages/hodie
+#DOCDIR=$(INSTALL_PATH)/doc/packages/hodie
 
 #############################
 # End of user configuration #
@@ -41,7 +41,7 @@
 $(OBJECTS): $(HEADERS)
 
 install: $(EXEC)
-	$(INSTALL) -s -m 755 $(EXEC) $(BINDIR)
+	$(INSTALL) -m 755 $(EXEC) $(BINDIR)
 	install -m 644 hodie.1 $(MAN1DIR)
 	install -d $(DOCDIR)
 	install -m 644 $(DOCS) $(DOCDIR)
