# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="BDFOY"

inherit perl-module

DESCRIPTION="Cookie storage and management for Mozilla"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="dev-perl/Text-Diff
	>=dev-perl/HTTP-Cookies-6.100.0
	dev-perl/DBD-SQLite
	dev-perl/DBI"
