# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Extra functions for working with optparse-applicative"
HOMEPAGE="https://hackage.haskell.org/package/optparse-applicative-dex"

LICENSE="ISC"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/optparse-applicative-0.17.1:=[profile?] <dev-haskell/optparse-applicative-1:=[profile?]
	>=dev-haskell/prettyprinter-1.7.1:=[profile?] <dev-haskell/prettyprinter-2:=[profile?]
	>=dev-haskell/text-1.11.1:=[profile?] <dev-haskell/text-3:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
