# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$
# This ebuild generated by g-cpan 0.16.0

EAPI=5

MODULE_AUTHOR="NWETTERS"

inherit perl-module

DESCRIPTION="Update timestamps, create nonexistent files"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""
