#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python
python:
    - pypy
env:
    - PORTAGE_VER="2.3.3"
before_install:
    - sudo apt-get -qq update
    - pip install lxml
before_script:
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr
    - mkdir -p travis-overlay /etc/portage /usr/portage/distfiles
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/.travis.yml" -O .travis.yml.upstream
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /usr/portage --strip-components=1
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /usr/portage/distfiles/metadata.dtd
    - ln -s portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - SIZE=$(stat -c %s .travis.yml.upstream)
    - if ! cmp -n $SIZE -s .travis.yml .travis.yml.upstream; then echo -e "\e[31m !!! .travis.yml outdated! Update available https://github.com/mrueg/repoman-travis \e[0m" > /tmp/update ; fi
    - cd travis-overlay
script:
    - ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full -d"
# You can append own scripts after this line
    - mv overlint-cli ..
    - cd ../portage-portage-${PORTAGE_VER}
    - python setup.py install || true
    - cd ../overlint-cli/overlint-0.5.3
    - python setup.py install
    - cd ../../travis-overlay
    - ./../spinner.sh "overlint-cli ."
    # We'd like to use pkgcore-based checks, but the snakeoil library won't compile on pypy.
    # - bash travis-repo-checks-master/run-tests.bash
before_install:
    - mkdir overlint-cli
    - cd overlint-cli
    - wget http://gentoo.osuosl.org/distfiles/overlint-0.5.3.tar.gz
    - tar xzf overlint-0.5.3.tar.gz
    - cd ..
    # - wget -O - "https://github.com/gentoo/travis-repo-checks/archive/master.tar.gz" | tar -xz
# install:
    # - bash travis-repo-checks-master/prepare-tests.bash
