.TH "BLOCKATTACK" "6" 
.SH "NAME" 
blockattack \(em Rise of the Blocks 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBblockattack\fR. 
 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
. 
.SH "OPTIONS" 
.PP 
These programs don't have specific option. 
.SH "AUTHOR" 
.PP 
This manual page was written by Goneri Le Bouder goneri@rulezlan.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Fri 25 Aug 2006, 16:18 
