.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XWORD 1 "December 3, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
xword \- do crossword puzzles in the Across Lite format
.SH SYNOPSIS
.B xword
.RI [ puzzlefile.puz ] ...
.SH DESCRIPTION
Xword is a GTK program for doing crossword puzzles. It can read and write
puzzles in the Across Lite file format. Consequently, it works well for doing
puzzles from The New York Times. As well as a clock, it supports printing. It
also auto-saves puzzles as you solve them so that you can return to partially
completed puzzles.
.SH USAGE
First, locate a puzzle on the web. The best place to go is the web site of The
New York Times. However, it costs money to access these puzzles. Free puzzles
are available from The Houston Chronicle.
.PP
After you have found a puzzle, click on it in your web browser. Xword will open
the puzzle and you can start solving. You can also choose to save the puzzle on
your hard disk. Then you can open the puzzle using Xword later.
.PP
After you have worked on a puzzle for a while, you may want to save your work.
There are two ways to save. The easiest way is to close Xword without any
further action. The next time you open the same puzzle (either by opening
the .puz file or by clicking the same link on the web), you will be asked
whether you want to continue where you left off. If you choose to continue, all
your correct and incorrect answers will be saved, as well as the time on the
clock.
.PP
However, this technique only works for opening the puzzle on the same computer.
If you need to open the saved puzzle on a different computer, then you can
choose "Save" from the "File" menu. The saved file can be opened with Xword on
any computer. However, incorrect answers and the time on the clock will not be
saved.
.PP
To print a puzzle, select "Print" from the "File" menu. You can see what the
printed puzzle will look like by clicking "Print Preview". You can select the
paper size and orientation by clicking on the "Paper" tab (puzzles are usually
easier to read in landscape mode).
.PP
Sometimes a puzzle will be locked so that the answers are unavailable.
Unfortunately, Xword's support for locked puzzles is somewhat flaky. When using
a locked puzzle, you should not click on the "Check" or "Solve" buttons, since
they will give incorrect information. However, you can still use Xword to enter
answers for a locked puzzle. Later, when an unlocked version of the puzzle is
released (usually the next day), open it using Xword. When asked, choose to
continue where you left off. Now you can use the "Check" and "Solve" buttons to
see how well you did. Sometimes crosswords will come with a four-digit code to
unlock a locked puzzle file. This code is not needed by Xword ...
.PP
For more information, see the project home page at <http://x-word.org>.
.SH AUTHOR
xword was written by Bill McCloskey <bill.mccloskey@gmail.com>. 
.PP
This manual page was written by John Sullivan <john@wjsullivan.net>,
for the Debian project (but may be used by others).
.SH BUGS
Please report bugs to <bill.mccloskey@gmail.com>.
