# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="WIML"
DIST_VERSION="1.00"


inherit perl-module

DESCRIPTION="Read and write Macintosh Finder DS_Store files"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="perl-gcpan/Mac-Carbon
	dev-perl/Test-NoWarnings
	dev-perl/Module-Build
	dev-lang/perl"
