.TH WXBANKER 1 "2 August 2009"
.SH NAME
wxBanker \- simple personal finance
.SH SYNOPSIS
.B wxbanker
.SH DESCRIPTION
.B wxBanker
allows you easily manage your finances by keeping track
of transaction in accounts. You can add, edit, and remove accounts and
transactions from a single view as well as see the balances of all
your accounts and a grand total. Click over to the Summary view for
a graph of your total balance over time.

By default, wxBanker auto-saves your information after each change,
so there is no need to manually save. However, auto-saving may be
disabled from the File menu.

.SH USAGE
wxbanker

.SH FILES
.I ~/.config/wxbanker/wxBanker.cfg
.RS
The configuration file which persists the state of the UI.
.RE
.I ~/.local/share/wxbanker/bank.db
.RS
The sqlite database which stores the accounts and transactions. For
schema information see the source file persistentstore.py.
.SH BUGS
See http://launchpad.net/wxbanker/+bugs for a list of bugs.

.SH AUTHOR
Authors of the program: see Launchpad - http://launchpad.net/wxbanker
