# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="BRIANDFOY"
DIST_VERSION="1.606"


inherit perl-module

DESCRIPTION="work with Mac plists at a low level"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="dev-perl/HTML-Parser
	dev-perl/XML-Entities
	dev-lang/perl"
