.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GNIALL 1 "November 29, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gniall \- A language learning program
.SH SYNOPSIS
.B gniall
.RI [ OPTIONS ]... 
.SH DESCRIPTION
This manual page documents briefly
.B gniall
, a language learning program for GNOME.
.SH OPTIONS
.B gniall
accepts the standard GNOME application options. Try `gniall --help' to
get more information about these options.
.SH AUTHOR
This manual page was written by Samuel Hocevar <sam@zoy.org>,
for the Debian GNU/Linux system (but may be used by others).
