# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# This ebuild generated by g-cpan 0.16.0

EAPI=5

MODULE_AUTHOR="DANKOGAI"

inherit perl-module

DESCRIPTION="JIS X 0212 (aka JIS 2000) Encodings"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64 x86"
IUSE=""

DEPEND="dev-lang/perl"
RDEPEND="dev-lang/perl"
