# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# This ebuild generated by g-cpan 0.16.0

EAPI=5

MODULE_AUTHOR="IANC"

inherit perl-module

DESCRIPTION="converter to SDF"

LICENSE="BSD-2"
SLOT="0"
KEYWORDS="amd64"
IUSE=""
