.\" (c) 2007 Miriam Ruiz <little_miry@yahoo.es>
.\" 
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH "fenix-fxi" "1" "0.92a" "" ""
.SH "NAME"
fenix\-fxi \- fenix interpreter
.SH "SYNOPSIS"
.B fenix\-fxi [filename.dcb]
.SH "DESCRIPTION"
This program executes the bytecode files compiled with fenix.
.PP 
If no parameter is given and it has a different name from it's standard one, like in a symbolic link, the program tries to open a binary file with the same name as the interpreter.
.PP 
options:
.TP 
\fB\-d\fR
Activate DEBUG mode
.TP 
\fB\-f\fR
16bpp Filter ON (only 16bpp color mode)
.PP 
.SH "SEE ALSO"
.BR fenix (1),
.BR fenix\-fxc (1),
.BR fenix\-fpg (1),
.BR fenix\-map (1)
