# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="KNTONAS"

inherit perl-module

DESCRIPTION="A Sleepy Mechanize Agent"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"

DEPEND=">=dev-perl/WWW-Mechanize-2.170.0"

# Seeing test failures, looking like timeouts caused by parallel emerges
# TODO: investigate once system idle again
RESTRICT="test"
