.\" Opticalraytracer manual page.
.\" (C)2010 D. Haley <mycae@yahoo.com>
.\"

.TH opticalraytracer 1 
.SH NAME
Opticalraytracer \- A virtual lens design workshop 
.SH DESCRIPTION 
OpticalRayTracer is an application that analyzes systems of lenses. It uses optical principles and a virtual optical bench to predict the behavior of many kinds of ordinary and exotic lens types. OpticalRayTracer includes an advanced, easy-to-use interface that allows the user to rearrange the optical configuration by simply dragging lenses around using the mouse.
 
.SH OPTIONS
This package has no options, and is controlled entirely through its graphical user interface.

.SH LICENCE
Opticalraytracer is Copyright (C) 2010 by Paul Lutus. Use this software at  your  own risk!   This  software  released  under the GNU General Public License v2.
Please read the COPYING file for more information.

.SH AUTHOR
This manpage was written by D. Haley <mycae@yahoo.com>
.SH HOMPEAGE
The opticalraytracer homepage may be found at \fPhttp://www.arachnoid.com/OpticalRayTracer/\fB 

