name: pkgcheck

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run pkgcheck
      # Switch back to pkgcore/pkgcheck-action@v1 once pkgcore/pkgcheck-action#4 is fixed
      uses: nabbi/pkgcheck-action@v1
      with:
        args: --keywords=-RedundantVersion,-MissingAccountIdentifier,-OldPackageUpdate
