name: pkgcheck

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
      with:
        args: --keywords=-RedundantVersion,-MissingAccountIdentifier,-OldPackageUpdate --profiles=-default/linux/amd64/17.0/musl,-default/linux/amd64/17.0/musl/clang,-default/linux/amd64/17.0/x32,-default/linux/amd64/17.0/musl/hardened,-default/linux/amd64/17.0/x32/systemd/merged-usr,-default/linux/amd64/17.0/musl/hardened/selinux,-default/linux/amd64/23.0/musl,-default/linux/amd64/23.0/musl/hardened,-default/linux/amd64/23.0/musl/hardened/selinux,-default/linux/amd64/23.0/split-usr/musl,-default/linux/amd64/23.0/musl/llvm,-default/linux/amd64/23.0/split-usr/musl/hardened,-default/linux/amd64/23.0/split-usr/musl/hardened/selinux,-default/linux/amd64/23.0/split-usr/musl/llvm,-default/linux/amd64/23.0/x32,-default/linux/amd64/23.0/split-usr/x32,-default/linux/amd64/23.0/x32/systemd,-default/linux/x86/23.0/i486/hardened,-default/linux/amd64/23.0/no-multilib/prefix/kernel-2.6.32+,-default/linux/amd64/23.0/split-usr/no-multilib/prefix/kernel-2.6.32+
