name: Repoman
on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 3 * *'
jobs:
  repoman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hacking-gentoo/action-repoman@master
